---
# RedHat tasks file for ansible-role-profile

- name: "Configure bashrc configuration file"
  ansible.builtin.replace:
    path: "{{ bashrc }}"
    regexp: '(?i)^(\s*umask\s.*)'
    replace: "\tumask {{ umask }}"
    state: present
    backup: yes

- name: "Configure profile configuration file"
  ansible.builtin.lineinfile:
    dest: "{{ profile }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  with_items:
    - regexp: ^[\s]*umask.*\b.*$
      line: "    umask {{ umask }}"
