---
# RedHat tasks file for ansible-role-profile

- name: "Configure bashrc configuration file"
  ansible.builtin.replace:
    path: "{{ bashrc }}"
    regexp: '(?i)^(\s*umask\s.*)'
    replace: "\tumask {{ umask }}"

- name: "Configure profile configuration file"
  ansible.builtin.replace:
    path: "{{ profile }}"
    regexp: '(?i)^(\s*umask\s.*)'
    replace: "\tumask {{ umask }}"

- name: "Configure login defaults configuration file"
  ansible.builtin.replace:
    path: "{{ login_defs }}"
    regexp: '(?i)^(\s*UMASK\s.*)'
    replace: "UMASK\t\t{{ umask }}"
