---
# RedHat tasks file for ansible-role-profile

- name: "Configure bashrc configuration file"
  ansible.builtin.lineinfile:
    dest: "{{ bashrc }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  with_items:
    - regexp: ^[\s]*umask.*\b.*$
      line: "       umask {{ umask }}"

- name: "Configure profile configuration file"
  ansible.builtin.lineinfile:
    dest: "{{ profile }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  with_items:
    - regexp: ^[\s]*umask.*\b.*$
      line: "    umask {{ umask }}"
